---
kind: pipeline
name: build-lambda
type: docker
platform:
  os: linux
  arch: arm64
steps:
  - name: build-docker
    image: plugins/ecr
    depends_on: [ clone ]
    settings:
      repo: 601394826940.dkr.ecr.us-west-2.amazonaws.com/my-ip
      region: us-west-2
      tags:
        - latest
        - ${DRONE_COMMIT}

  - name: deploy-clustermaestro
    image: ktruckenmiller/ansible:arm
    depends_on: [build-docker]
    environment:
      AWS_DEFAULT_REGION: us-west-2
      VERSION: ${DRONE_COMMIT}
      SERVICE_NAME: my-ip
      CLUSTER: production-kloudcover-v3
      PRIORITY: 17
      COUNT: 2

    commands:
      - ansible-playbook -i ansible_connection=localhost deploy.yml -vvv
