---
kind: pipeline
name: build-lambda
steps:
  # - name: build-docker
  #   image: plugins/docker
  #   depends_on: [ clone ]
  #   settings:
  #     repo: ktruckenmiller/my-ip
  #     tags:
  #       - ${DRONE_COMMIT}
  #       - latest
  #     username:
  #       from_secret: username
  #     password:
  #       from_secret: password
  #     when:
  #       branch: [master]
  #       event: [push]

  - name: build-docker
    image: plugins/ecr
    depends_on: [ clone ]
    settings:
      repo: 601394826940.dkr.ecr.us-east-2.amazonaws.com/my-ip
      region: us-west-2
      tags:
        - latest
        - ${DRONE_COMMIT}

  - name: deploy-clustermaestro
    image: ktruckenmiller/ansible
    depends_on: [build-docker]
    environment:
      AWS_DEFAULT_REGION: us-west-2
      VERSION: ${DRONE_COMMIT}
      SERVICE_NAME: my-ip
      CLUSTER: kloudcover
      PRIORITY: "17"

    commands:
      - ansible-playbook -i ansible_connection=localhost deploy.yml -vvv

  - name: deploy-jamf
    image: ktruckenmiller/ansible
    depends_on: [build-docker]
    environment:
      AWS_DEFAULT_REGION: us-west-2
      VERSION: ${DRONE_COMMIT}
      SERVICE_NAME: jamf
      CLUSTER: staging-kloudcover
      PRIORITY: "21"
    commands:
      - ansible-playbook -i ansible_connection=localhost deploy.yml -vvv
