---
- hosts: localhost
  gather_facts: false
  vars:
    name: jamf
    vpc: vpc-9aab64f3
    template: service.yml
    hosted_zone: clustermaestro.com

  tasks:
    - name: cloudformation
      cloudformation:
        stack_name: "{{name}}-ecs"
        state: present
        region: "{{region}}"
        template: "service.yml"
        template_parameters:
          ServiceName: "{{ name }}"
          HostedZone: "{{hosted_zone}}"
          Environment: "{{environ}}"
          Priority: "17"
          Vpc: "{{vpc}}"
          CertId: 89eb20e3-7dad-489a-ad1a-619cae4a2c29
          Version: latest
          Subnets: subnet-0c00ee77,subnet-a6954dcf,subnet-d65b579c
          ClusterName: "{{environ}}-{{name}}"
