---
- hosts: localhost
  gather_facts: false
  vars:
    name: my-ip
    vpc: vpc-849531e0
    region: us-west-2
    template: service.yml
    hosted_zone: clustermaestro.com

  tasks:
    - name: cloudformation
      cloudformation:
        stack_name: "{{name}}-ecs"
        state: present
        region: "{{region}}"
        template: "service.yml"
        template_parameters:
          VpcId: "{{ vpc }}"
          ServiceName: "{{ name }}"
          HostedZone: "{{hosted_zone}}"
          Environment: prod
          Priority: "17"
          CertId: 619c392f-3539-4951-b2b9-89fb2dca27d9
          Version: "{{ lookup('env', 'VERSION') }}"
